services:
  - type: web
    name: wordsworth-bot-service
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: TELEGRAM_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
